### ISSUE TITLE
CTkTable Installation Issue when using pip installer

### ISSUE THREAD

**Issue by ISAACLINDROOS** [Akascape/CTkTable#1]
@Akascape Is it possible for this to be packaged as part of the CTK Master Library?

`ERROR: Could not find a version that satisfies the requirement ctktable (from versions: none)`
`ERROR: No matching distribution found for ctktable`

[https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/__init__.py](url)

**Comment by Akascape** [comment]
@ISAACLINDROOS 
CTkTable is not published to pypi, so no pip installation is available for now. 

But you can paste the ctktable.py file inside customtkinter and add `from .ctktable import CTkTable` in the `__init__.py` file.

**Comment by ISAACLINDROOS** [comment]
> @ISAACLINDROOS CTkTable is not published to pypi, so no pip installation is available for now.
> 
> But you can paste the ctktable.py file inside customtkinter and add `from .ctktable import CTkTable` in the `__init__.py` file.

inside of the `/lib` file path or the `/lib/customtkinter` file path?

**Comment by Akascape** [comment]
@ISAACLINDROOS 
Inside the customtkinter folder.

**Comment by ISAACLINDROOS** [comment]
@Akascape

Cannot import name 'CTkTable' from 'customtkinter.windows.widgets'

Any ideas? :)

**Comment by Akascape** [comment]
@ISAACLINDROOS Please follow this: https://github.com/Akascape/CTkTable/issues/2#issuecomment-1558506223

**Comment by ISAACLINDROOS** [comment]
> @ISAACLINDROOS Please follow this: [#2 (comment)](https://github.com/Akascape/CTkTable/issues/2#issuecomment-1558506223)

Will do, Thanks You.
