### ISSUE TITLE
Table doesn't show on CtkScrollableFrame

### ISSUE THREAD

**Issue by timursper-apps** [Akascape/CTkTable#103]
`frame = ctk.CTkScrollableFrame(root, orientation="horizontal", width=600, fg_color="transparent")
frame.place(x=300, y=28)

studentsTable =CTkTable(frame, values=studentsTableList, width=300)
studentsTable.place(x=0, y=28)

marksTable = CTkTable(root, values=marksTableList, write=1)
marksTable.place(x = 300, y = 28)`

How can I fix it?

**Comment by Akascape** [comment]
@timursper-apps Place method can't be used in ctkscrollable frame currently (not even with other widgets).
Try pack or grid methods.
