### ISSUE TITLE
How to get value of selected row?

### ISSUE THREAD

**Issue by DeidadDev** [Akascape/CTkTable#115]
I tried the methods of the docs, but my program works with a function and should be after the self.table declaration as variable. If i use lambda I get the error `TypeError: App.home.<locals>.<lambda>() takes 0 positional arguments but 1 was given`

I need pass the last value to a function, but even I cant pass first the last value of the row. Help me.

**Comment by Akascape** [comment]
@DeidadDev Refer here: https://github.com/Akascape/CTkTable/issues/29#issuecomment-1627278004
