### ISSUE TITLE
CTkTables behaviour exactly like ttk.treeview?

### ISSUE THREAD

**Issue by MORBH177** [Akascape/CTkTable#17]
Hi again, 

first, sorry did not found the issues-section before. 

I like to use the CTkTable instead of a ttk.treeview in my project. 
But i can not get the CTKTable behaviour exactly like ttk.treeview? 
Is there anyone who has written some functions which let the CTKTable behave like the original TreeView Widget ? 

issues i got:
-First, the Hover Event is not working with "edit_row" (when i hover over with my mouse pointer it only selects a single cell)
-Second, when i click on a particular row, i want the clicked row to colored differently (returning the rows values is not an issue anymore) It is always taking the Style attributes from CTKFrame, and CTkButton (maybe a suggestion to create an own Section for Styling in CTk-Style-File, have you connected to Shimansky right now for implementation in the original library?)

i would highly appreciate this.

**Comment by dishb** [comment]
A table and treeview are two very different widgets. I don't think you can get the table to behave like a treeview widget without completely making a new widget... 

> Is there anyone who has written some functions which let the CTKTable behave like the original TreeView Widget ?
No one has yet.

**Comment by Akascape** [comment]
@MORBH177 
No, this is only a table widget to display tabular data.
If you are looking for a dropdown type treeview, you can refer this: https://github.com/TomSchimansky/CustomTkinter/discussions/524#discussioncomment-3898307

If you want a modern theme for that tk treeview table, use this theme: https://github.com/rdbende/Sun-Valley-ttk-theme
