### ISSUE TITLE
Incorrect data being returned for command

### ISSUE THREAD

**Issue by dishb** [Akascape/CTkTable#18]
I've got the following code that sets up a `CTkTable` widget with a function for the command.
```python
self.table = CTkTable(master = self,
                      font = self.font,
                      values = self.values,
                      command = self.disconnect_device,
                      height = self.height + 10,
                      )
```
The function `self.disconnect_device` takes one argument like so:
```python
def disconnect_device(self, data: dict):
    print(data)
```
I'm using an object oriented approach hence the `self` in the function definition.

The issue is that when I print the value of `data`, I'm getting incorrect values. I've determined this is not due to my code, though I could be wrong. For example, I clicked on the 2nd row (index of 1) and in my terminal, I got the correct value. Upon clicking the third row (index of 2), I got the value for the first row.

I keep getting incorrect data passed to my function.

**Comment by Akascape** [comment]
@dishb Not experiencing this issue. Can you try this example and see the result: https://github.com/Akascape/CTkTable/issues/6#issuecomment-1570224204

Also, can you tell what table operations you did?

**Comment by dishb** [comment]
![Screen Shot 2023-06-25 at 10 29 51 AM](https://github.com/Akascape/CTkTable/assets/130259005/1b538068-43d7-4891-8e1e-1fb892f8ce70)
All the values printed to my terminal (by clicking the cells in the table) are correct...

Looks like an issue with my code... Thank you.
