### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ISAACLINDROOS** [Akascape/CTkTable#2]
[Update README.md](https://github.com/Akascape/CTkTable/commit/008acc5db0d33c8dc819726cbcfb36271f08908a)

Following on from #1, `README.md` needs to be updated to further expand on the process of package installation.

> Download the source code, paste the CTkTable folder in the directory where your program is present.

- How is this package installed?
- Where is it installed to?
- Folder structure?
- Screenshots or images?

**Comment by Akascape** [comment]
@ISAACLINDROOS 
I guess you are a beginner.

But nevermind, I will try to explain the installation process.

All modules installed with pip are stored inside the `lib/site-packages` of python folder.
The modules are basically a folder and the python interpreter searches the installed modules automatically from that lib folder when you try to import them.

Modules can also be imported if you have them in the same folder 📁 where your example is also present. 

The folder structure looks like this:

```
base-directory
  ↳ CTkTable
      ↳ __init__.py
      ↳ ctktable.py
  ↳ example.py
```

CTkTable is a separate module currently not uploaded to pip, so it is advised to use it like this.
This is not a official widget under customtkinter but made with customtkinter, so you have to import it separately using `from CTkTable import CTkTable`.

I hope it clears your doubts.

**Comment by ISAACLINDROOS** [comment]
Awesome, Thank you for your help.

**Comment by sathyarajshetigar** [comment]
Can we use tags to identify rows?  Something similar to tkinter tables?

**Comment by sathyarajshetigar** [comment]
> 

In my previous implementation which I am planning to replace with this, I use tags when creating new rows and use the same to find rows later.
I used ttk from tkinter module. 
This is how I insert new row
self.table.insert("", "end", tags=tag, values=(Symbol, qty, entryPrice, ltp, unrealized,tsl))

To update data
  for row in self.table.get_children():
            if self.table.tag_has(tag, row):
                self.table.item(row, values=(Symbol, qty, entryPrice, ltp, round(unrealized), round(tsl)))
                

To remove row
 for row in self.table.get_children():
            if self.table.tag_has(tag, row):
                self.table.delete(row)
                
Looking to achieve similar behaviour

**Comment by Akascape** [comment]
@sathyarajshetigar You can do all the operation by passing the proper index for row/column methods. Please go through the documentation once and test them.
I recommend you not to use this widget if you have some big tabular data.
