### ISSUE TITLE
[Bug] random chunk of column missing

### ISSUE THREAD

**Issue by dishb** [Akascape/CTkTable#23]
![Screen Shot 2023-06-27 at 5 24 07 PM](https://github.com/Akascape/CTkTable/assets/130259005/c9bcce63-4f65-4765-8863-ec64a222cd88)
No traceback errors...

macOS 12.6.7
Python 3.11.3
CustomTkinter 5.2.0
CTkTable 0.6.0

**Comment by Akascape** [comment]
@dishb  That was happening if you pass this "" value. But its fixed now!
