### ISSUE TITLE
Change the width of a column

### ISSUE THREAD

**Issue by sim2511** [Akascape/CTkTable#25]
Hello, 
Is it possible to change the width/height of a column ? My data contained in processed_messages are > to the width of the column. It's due to "write=1" parameter, I do not have this issue without this parameter

my example:

    table = CTkTable(master=scrollable_frame, row=len(processed_messages), column=5, values="",text_color="black",write=1)
    table.grid(row=4, column=0, pady=5, padx=5, columnspan=2, sticky="nsew")

    for i in range(len(processed_messages)):
        table.insert(row=i, column=0, value=processed_messages[i])
        table.insert(row=i, column=1, value=heure_messages[i])

**Comment by diamant3** [comment]
Maybe you can use `configure(width=value, height=value)`(value is an integer), but it's for the table, not the cell's width or height.

**Comment by Akascape** [comment]
@sim2511 Use `table.edit_column(column_num, width=1)`
