### ISSUE TITLE
How can we edit the data of a row?

### ISSUE THREAD

**Issue by HassanAnari** [Akascape/CTkTable#30]
Hello again, thanks for this: https://github.com/Akascape/CTkTable/issues/29
I need three functions for my application: add row, edit row and delete row. Adding and deleting is good, but editing can be better. I looked at this issue: https://github.com/Akascape/CTkTable/issues/13 but it conflict with row selection. Is there a way that when a row is selected and the edit button is clicked, that row data can be edited? Without opening a new page and inside the table.
Thank you for your time.

**Comment by Akascape** [comment]
@HassanAnari In that case you have to use the entry boxes. Use `write=1` in table parameter for live editing.
Otherwise you will have to add a popup menu.

**Comment by HassanAnari** [comment]
I understand, so I will make a page for editing. Thank you for your reply.
