### ISSUE TITLE
header_color issue

### ISSUE THREAD

**Issue by paichiwo** [Akascape/CTkTable#44]
header_color accepting str only, but should also accept a tuple(str, str)
When tuple of colors provided `header_color = ("#111111", "#777777")`, it shows up in the code editors as an error.

when only one str provided header_color doesn't change when the system theme changes to light or dark so customtkinter base functionality is lost.

adding tuple to line 26 seems to work fine and fix this issue: `header_color: str or tuple = None,`

**Comment by Akascape** [comment]
@paichiwo Header can only be a single color.

**Comment by paichiwo** [comment]
Thats true header is one color but you can specify one for dark mode and one for light mode , when tuple provided then you have a color for light mode and dark mode. Every ctk widget can have one str for the color or tuple for dark mode color and light mode color, example: 
```
button = customtkinter.CTkButton(master=root_tk,
                                 fg_color=("black", "lightgray"),  # <- tuple color for light and dark theme
                                 text="CTkButton",
                                 command=button_event)
```
[Source customtkinter docs](https://pypi.org/project/customtkinter/0.3/)
