### ISSUE TITLE
Hover Color

### ISSUE THREAD

**Issue by bem21454** [Akascape/CTkTable#46]
The cells along each corner do not color correctly when hover is enabled. When hovering over the cell, all four corners have a radius on them despite the cell only having one rounded corner.
![Table_hover_issue](https://github.com/Akascape/CTkTable/assets/117242054/5074aeab-dcdf-473a-b712-6bb65dd26161)

**Comment by Akascape** [comment]
@bem21454 To be honest, this should be an issue of ctkbutton.

**Comment by RuzickaTomas** [comment]
This is because you have enabled_hover_color, but you are not changing dynamically bg_color (https://customtkinter.tomschimansky.com/documentation/color). You will possibly need to override default hover with your own implementation, that would include this behavior.

**Comment by Akascape** [comment]
@bem21454 @RuzickaTomas Thanks for the suggestion, I have implemented my own hover method. Please update the package.
