### ISSUE TITLE
Scrollable cells

### ISSUE THREAD

**Issue by segasa9342** [Akascape/CTkTable#47]
First of all, THANK YOU for this great library. 

I'm currently working on showing a dataframe of texts (long strings). 

My question concerns scrollable cells. 
What I want to display is a table in which cells are scrollable, so that only the first few words are shown and then the user can navigate the rest of the text to read the full string. 

My code looks like this. 

```
self.df = pd.DataFrame(self.lists).transpose().values.tolist()  #transposition for the correct order 

self.label = customtkinter.CTkLabel(self, text="ToplevelWindow")
self.label.pack(padx=20, pady=20)

self.table = CTkTable(master=self, row=0, column=3, values=[self.df])
self.table.pack(pady=20, padx=20)
```

Apart from the issues that I have mentioned, this code works fine.

Thanks in advance!

**Comment by Akascape** [comment]
@segasa9342 Not possible currently, try tksheet https://github.com/ragardner/tksheet
