### ISSUE TITLE
How to add horizantal and vertical scrollbar to the CtkTable

### ISSUE THREAD

**Issue by sunny9495-dev** [Akascape/CTkTable#53]
Hi,

First of all, Thank you for the great library.

I just want to know how we can add horizontal and vertical scrollbar to CTkTable.

Any example is appreciated.

Thanks.

**Comment by Akascape** [comment]
@sunny9495-dev Use my CTkXYFrame which has both horizontal and vertical scrollbar : https://github.com/Akascape/CTkXYFrame/assets/89206401/859b6733-3c91-4093-a511-d6f1060a18ca

![Screenshot](https://github.com/Akascape/CTkXYFrame/assets/89206401/859b6733-3c91-4093-a511-d6f1060a18ca)

I hope you know that for one scrollbar you can use the ctkscrollable frame. For both scrollbar use CTkXYFrame.

**Comment by sunny9495-dev** [comment]
Hi @Akascape

Thank you for the quick response.

I tried the `place` instead of `pack` but its not working

Here is the code I tried.

`frm_cscan_widgets = CTkXYFrame(master=root, width=200, height=150)
frm_cscan_widgets.place(x=10, y=140)`

I see the width, height isn't working. Here is the screenshot

[https://i.imgur.com/CJ5s6no.png](https://i.imgur.com/CJ5s6no.png)

Any help would be appreciated.
