### ISSUE TITLE
Is there a better solution regarding rendering when adding rows?   

### ISSUE THREAD

**Issue by childeyouyu** [Akascape/CTkTable#67]
Each time a row is added it takes longer to render the entire table, which is visually fatiguing, and frequently updated tables can be difficult to read. Is it possible to render only the last part of the table when adding a row?

Attached is the code I use:

---

每次添加一行后都需要较长的时间进行渲染整个表格，视觉上会疲劳，而且经常更新的表格会看不清。能否在添加行时只在最后部分进行渲染?

附上我使用的代码：
```
data = [["设备", "通道", "时间", "值"]]
    scrollable_frame_form = customtkinter.CTkScrollableFrame(frame_form, height=200)
    scrollable_frame_form.pack(fill="both", expand=True)
    table = CTkTable(master=scrollable_frame_form, column=4, values=data)
    table.pack(fill="x", padx=20, pady=20)
    while True:
        time.sleep(1)

        conn = sqlite3.connect("data.db")
        c = conn.cursor()
        data = c.execute(
            "SELECT device_name,channel,datetime,value FROM data where device_name =? and channel =?",
            ("设备 1", "通道 1"),
        )
        data = data.fetchall()
        data = [data[-1][0], data[-1][1], data[-1][2], data[-1][3]]
        print(data)
        table.add_row(values=data)
```
![image](https://github.com/Akascape/CTkTable/assets/89082776/c4bdd3d0-a21c-4bc2-8f7f-b21615e07798)

**Comment by Akascape** [comment]
@childeyouyu Currently not possible with this version. I know but maybe in future i will change replace the ctk button class with some optimised cell widget.

**Comment by childeyouyu** [comment]
Thanks for the reply, looking forward to the new features and I'll keep an eye on your project.
---

感谢你的回复，期待新功能的加入，我会持续关注你的项目。

**Comment by childeyouyu** [comment]
I apologize for opening this issue again, but I thought someone with the same needs as me might see my solution as a temporary addition.
My solution is to set up multiple tabels with the same spacing and then update the data in a thread to create the illusion that they are the same tabel, admittedly an immature idea, but I hope that until a new solution comes along, it will help people who have the same need as I do.
https://youtu.be/eOvYKR3DmJY?si=jdj2dD0jJHCRAFhb
I'll close the issue later in the day
```
import time
from threading import Thread

import customtkinter
from CTkTable import *


def thread_function(num):
    for i in num:
        values = [i]
        table_value = CTkTable(
            master=scrollable_frame_form, column=5, values=values, corner_radius=0
        )
        table_value.pack(fill="x")
        time.sleep(1)


if __name__ == "__main__":
    root = customtkinter.CTk()
    data = [["设备", "通道", "时间", "值", "占位"]]
    scrollable_frame_form = customtkinter.CTkScrollableFrame(
        root, height=200, corner_radius=0
    )
    scrollable_frame_form.pack(fill="both", expand=True)

    table = CTkTable(
        master=scrollable_frame_form, column=5, values=data, corner_radius=0
    )
    table.pack(fill="x")

    num = [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
    ]
    thread_table = Thread(target=thread_function, args=(num,))
    thread_table.start()

    root.mainloop()
```
很抱歉我再次打开这个issue，但我想与我有同样需求的人或许会看到我的解决方案,以此做为一个临时的补充.

我的解决方案是,设置间距相同的多个tabel,然后在一个线程中更新数据,造成他们是同一个tabel的假象,诚然他是一个不成熟的想法,但我希望在新的方案出现之前,可以帮助和我有同样的需求的人.
