### ISSUE TITLE
Table not working in frame 

### ISSUE THREAD

**Issue by OrewaNindo** [Akascape/CTkTable#71]
So i was writting a code and noticed that the table is not showing if i use it on a frame i can only use it in root application which arises a issue for apps like the one im creating with multiple frames...

**Comment by Akascape** [comment]
@OrewaNindo Not at all facing this issue. If you are using in virtual env, then customtkinter itself is buggy in that environment. also let me know which os you are using and your python version.

**Comment by Akascape** [comment]
However, check updating ctktable and python

**Comment by TheScriptingChauhan** [comment]
On a seperate file when i tried this table it didnt work on frame but it did work if i changed it to root looks like i must have forgot to pack frame but check this snippet even if i didnt use '-fg_color' it shows -fg_color issue. I had to set a colors to resolve it ... is this error coming cus i installed too many libs?
```
value = [["Website","Username","Password"],
             ["Amazon","Suraj","1234"]]
    
    n=len(value)

    table = CTkTable.CTkTable(
        master=home_frame,
        row=n,
        column=n,
        values=value,
        hover=True,
        height=900,
        width=1080
    )
    table.pack()

```

**Comment by Akascape** [comment]
@OrewaNindo When you post an issue, also write down the error message if any, or the screenshot.

**Comment by SMILEYwritez** [comment]
ohh ya sorry i had forgotten about it thanks for reminding!!!!
