### ISSUE TITLE
Table is doing this padding automatically

### ISSUE THREAD

**Issue by xdotstudio** [Akascape/CTkTable#73]
Hi, I'm doing a inventory program with the CTkTable, now, the table is doing this padding automatically, is there any way i can change it? I would love to be able to add a constant padding on every cell, also, big beginner here, it's just my first program.

![Captura de pantalla 2024-01-25 155604](https://github.com/Akascape/CTkTable/assets/153344946/18557bcf-6bba-4659-8adf-e82b5b9fbecb)

On the row of ID, and the 4th, you can see the additional padding, here's my code if needed:

        self.products_table = CTkTable(
            self, column=9, wraplength=250, values=products, padx=5, pady=5, anchor=W)
        self.products_table.grid(
            row=0, column=0, sticky=NSEW, padx=10, pady=10)
        default_table_labels = ["ID", "Name", "Description",
                                "Brand", "Category", "Tag", "Price", "Qty", "SKU"]
        self.products_table.add_row(index=0, values=default_table_labels)

I'm using a scrollable frame so all the entries of the database gets shown correctly

Thanks in advance, and cheers for this cool add-on

**Comment by Akascape** [comment]
@xdotstudio Don't add padx and pady in ctktable parameters.
