### ISSUE TITLE
Hidden column

### ISSUE THREAD

**Issue by ghost** [Akascape/CTkTable#82]
Hello,

Is it possible to have hidden column ?

Regards

**Comment by Akascape** [comment]
@sim2511 This is more a logical question, you can change the list values and update the table.

**Comment by ghost** [comment]
My table consists of four data columns, but I need one of them to be invisible to the user. This hidden column is crucial because it contains data that I use to interact with an API.

However, even though this column should not be displayed, its values are essential for data filtering operations. I need to always retrieve this column's value based on the current row's context.

**Comment by ghost** [comment]
self.hidden_columns = set()
    def set_column_hidden(self, column_index, hidden=True):
        """Masquer ou afficher une colonne."""
        if hidden:
            self.hidden_columns.add(column_index)
        else:
            self.hidden_columns.discard(column_index)
        self.update_table_display()
        
    def update_table_display(self):
        for row in range(self.rows):
            shift = 0 
            for column in range(self.columns):
                cell_widget = self.frame[row, column]
                if column in self.hidden_columns:
                    cell_widget.grid_forget()
                    shift += 1 
                else:
                    cell_widget.grid(row=row, column=column-shift)

example in code:
table.set_column_hidden(2, hidden=True)
